### ISSUE TITLE
Why the empty repo?

### ISSUE THREAD

**Issue by ghost** [ChimneySwift/Enhanced-Chat#2]
Why does this repo feel so empty? init.lua has nothing in it....

**Comment by LoneWolfHT** [comment]
lol
jk
Waiting for a response to the PR

**Comment by ChimneySwift** [comment]
because I'm a lazy butt and I have been distracted with other stuff.

:P ;)

**Comment by LoneWolfHT** [comment]
The repo is no longer empty.
